services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-mgmt-app
    container_name: task-mgmt-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - task-mgmt-network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: task-mgmt-nginx
    ports:
      - "5020:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - task-mgmt-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: task-mgmt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task-mgmt
      MYSQL_USER: task-mgmt
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - task-mgmt-network
    ports:
      - "3305:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task-mgmt-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: task-mgmt
      PMA_PASSWORD: secret
    ports:
      - "5021:80"
    networks:
      - task-mgmt-network
    depends_on:
      - db

volumes:
  db_data:

networks:
  task-mgmt-network:
    driver: bridge
